### ISSUE TITLE
Adding node to Home Assistant Node-red

### ISSUE THREAD

**Issue by PMu1** [bmdevx/node-red-contrib-remote-two#1]
Hi, 

I've been trying to add this node to Home Assistant Node-red, but cannot find it in Palette manager, nor can I install it. 

How can it be added? 

Thanks

**Comment by bmdevx** [comment]
Currently this is not in the palette for NodeRED. There are a few issues with the integration library and once unfolded-circle takes the library out of beta I will update the nodes and publish it to the palette. If you want to install it you can via npm into the NodeRED instance.
